version: '3.6'

services:
  geth:
    image: ethereum/client-go:alltools-{1.10.10}
    restart: always
    command: |
      --rpc
      --rpcaddr=0.0.0.0
      --rpcport=8545
      --port=30303
      --rinkeby
      --rpcapi="admin,db,debug,personal,eth,net,web3"
      --rpccorsdomain="*"
      --rpcvhosts="*"
      --syncmode="fast"
      --cache=2048
    volumes:
      - /geth:/root/.ethereum/
    ports:
      - "30303:30303"
      - "8545:8545"
    expose:
      - "8545"
      - "30303"
